apiVersion: v1
kind: Service
metadata:
  name: {{ include "predictive-lb.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "predictive-lb.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
  selector:
    {{- include "predictive-lb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
