apiVersion: v1
kind: Service
metadata:
  name: {{ include "predictive-lb.fullname" . }}-loadbalancer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "predictive-lb.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
spec:
  type: {{ .Values.loadBalancer.service.type }}
  ports:
    - port: {{ .Values.loadBalancer.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "predictive-lb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
