apiVersion: v1
kind: Service
metadata:
  name: {{ include "predictive-lb.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "predictive-lb.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: 9090
      protocol: TCP
  selector:
    {{- include "predictive-lb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
