apiVersion: v1
kind: Secret
metadata:
  name: {{ include "predictive-lb.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "predictive-lb.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ required "postgres.auth.password is required" .Values.postgres.auth.password | b64enc | quote }}
  grafana-password:  {{ required "grafana.adminPassword is required"  .Values.grafana.adminPassword   | b64enc | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s-postgres:5432/%s" .Values.postgres.auth.username .Values.postgres.auth.password (include "predictive-lb.fullname" .) .Values.postgres.auth.database | b64enc | quote }}
