{
 "title": "loadbalancer",
 "time": { "from": "2026-02-19T21:35:53.495Z", "to": "2026-02-19T21:48:26.662Z" },
 "panels": [
  {
   "title": "A* Server Scores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "astar_server_scores", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "Q-Learning: Reward & Epsilon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "qlearning_current_reward", "legendFormat": "{{Reward}}" },
    { "expr": "qlearning_epsilon", "legendFormat": "{{Epsilon}}" }
   ]
  },
  {
   "title": "Q-Learning Scaling Actions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(qlearning_actions_total[5m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(loadbalancer_cache_hits_total[1m]))\r\n/\r\n(\r\n  sum(rate(loadbalancer_cache_hits_total[1m]))\r\n  +\r\n  sum(rate(loadbalancer_cache_misses_total[1m]))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(loadbalancer_request_latency_seconds_bucket[1m]))",
     "legendFormat": "{{P50}}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(loadbalancer_request_latency_seconds_bucket[1m]))",
     "legendFormat": "{{P95}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(loadbalancer_request_latency_seconds_bucket[1m]))",
     "legendFormat": "{{P99}}"
    }
   ]
  },
  {
   "title": "Active Servers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "loadbalancer_active_servers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traffic: Current vs Predicted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(loadbalancer_requests_total[1m])",
     "legendFormat": "{{Current Traffic}}"
    },
    {
     "expr": "loadbalancer_predicted_traffic_5min",
     "legendFormat": "{{Prophet Prediction}}"
    },
    {
     "expr": "loadbalancer_prediction_upper_bound",
     "legendFormat": "{{UpperBound}}"
    },
    {
     "expr": "loadbalancer_prediction_lower_bound",
     "legendFormat": "{{Lower Bound}}"
    }
   ]
  }
 ]
}