# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"\xe3\x01\n\x10TelemetryPayload\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63pu_percent\x18\x02 \x01(\x02\x12\x16\n\x0ememory_percent\x18\x03 \x01(\x02\x12\x17\n\x0f\x61\x63tive_requests\x18\x04 \x01(\x05\x12\x1c\n\x14\x61vg_response_time_ms\x18\x05 \x01(\x02\x12\x16\n\x0e\x63\x61\x63he_hit_rate\x18\x06 \x01(\x02\x12\x14\n\x0ctimestamp_ns\x18\x07 \x01(\x03\x12\x16\n\x0etotal_requests\x18\x08 \x01(\x05\x12\x12\n\ncache_size\x18\t \x01(\x05\"*\n\x03\x41\x63k\x12\x10\n\x08received\x18\x01 \x01(\x08\x12\x11\n\tserver_id\x18\x02 \x01(\t2V\n\x10TelemetryService\x12\x42\n\x0fStreamTelemetry\x12\x1b.telemetry.TelemetryPayload\x1a\x0e.telemetry.Ack(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYPAYLOAD']._serialized_start=31
  _globals['_TELEMETRYPAYLOAD']._serialized_end=258
  _globals['_ACK']._serialized_start=260
  _globals['_ACK']._serialized_end=302
  _globals['_TELEMETRYSERVICE']._serialized_start=304
  _globals['_TELEMETRYSERVICE']._serialized_end=390
# @@protoc_insertion_point(module_scope)
